<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobsRFB-FileOperations-DryRunsExtent_20221118_180337</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>37c1e08d-c0cf-45a6-9de2-b4789ed47077</testSuiteGuid>
   
<testCaseLink>
      <guid>3eb5a10a-9972-4dc8-bdb8-cc05a8b66d21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>67e150e7-d6c1-4380-8e4f-696558567c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-MultiFileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>12db675c-16c4-4b33-923e-3e90b3058e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>b92913c3-e2c8-41b6-ac34-0471f3e92e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>efeae6f4-3f3e-4588-8af0-34464c4bba6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffa7487-f9f3-4b2a-9f86-0246012527f7</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>d69712fe-4c49-49b0-9d26-da5e0cdabea6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileViewerOps</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8be63bac-385b-407f-a237-9775212153c1</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,2,3,4,5,6,7,8,9,10,11,12</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileViewer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b5d174-8326-4309-a461-a3a8b349eae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>9b065ca7-abb9-4e53-9e42-92fff2b43874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>c398326f-2040-448d-b714-a3071a0cdb4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bfd2275-d015-4425-85f4-42fe0a1e3d40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>33e3f1bb-053e-464d-a46d-f795250201eb</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>7e845faf-e890-4be9-baa3-f07c4dba1c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobFiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea55ab9f-206e-4fcf-9ae0-7848cbada80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea661e7b-c276-42ef-a6c9-1c1ef53f2265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d599e9-d250-4bbc-8dc9-b8509e150c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd0c7cf-20ad-4071-a100-4a42f1e373db</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>b1c73871-9c46-4945-8946-10b98fbaad55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>e8d398ba-7706-492c-bb9c-2b1bd4be8ffe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmissionForLastSubmitted</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>71100be0-cee7-40fc-b219-491472ab76f5</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>13,14</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2165b182-636d-4b7f-ade2-161fca571166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc34a078-3b76-4c35-9aca-e5bdde596154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71100be0-cee7-40fc-b219-491472ab76f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>8593a4b9-9f88-428e-ba17-b836e798acf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5d3486-4f6d-4c60-b9f7-f852e8083cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ecc3a3-627b-4125-86fb-cb2431021897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d935056-a60a-4f76-a4d1-527bbd6f770d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c1226f-d56d-4cdf-ab0d-cd98ce0d3fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71100be0-cee7-40fc-b219-491472ab76f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>0d0853fe-9935-4957-956d-2f65728efe35</variableId>
      </variableLink>
   </testCaseLink>
<testCaseLink>
      <guid>b5fe689d-fa78-472f-822a-d6f9a5c4d28a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d092280c-55eb-4a78-af85-fffafe1f88e0</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
